language: java
jdk:
  - openjdk8
script:
- mvn package -Dmaven.test.skip=true
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 47.116.140.61
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
after_success:
- ssh ubuntu@47.116.140.61  "./your_shell-script.sh"
