---
name: network001
version: 1.0.0
client:
  organization: Org3
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org3:
    mspid: Org3MSP
    peers:
    - peer0.org3.ccb.com
    - peer1.org3.ccb.com
    certificateAuthorities:
    - ca


orderers:
  orderer3.ccb.com:
    url: grpcs://47.116.140.61:7050
    grpcOptions:
      ssl-target-name-override: orderer3.ccb.com
      hostnameOverride: orderer3.ccb.com
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAe2gAwIBAgIQCiwkvkSImGviDJW0vyotPDAKBggqhkjOPQQDAjBuMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEVMBMGA1UEChMMb3JnMy5jY2IuY29tMRswGQYDVQQDExJ0bHNjYS5v
        cmczLmNjYi5jb20wHhcNMjAxMTA5MDU0NTAwWhcNMzAxMTA3MDU0NTAwWjBuMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEVMBMGA1UEChMMb3JnMy5jY2IuY29tMRswGQYDVQQDExJ0bHNjYS5v
        cmczLmNjYi5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQXoPFffmXYrOUm
        qN4MxfAp5NLgxvYhC1NNcXwH5NOAR8MpVVUvVYraDLyTOcVD85ek/A4C/ojms4Do
        kWKmwGtFo20wazAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIG
        CCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIG6HuNurXNhtV7X7
        OvlZanG2DKegu2PBl3tHZ0UCteUTMAoGCCqGSM49BAMCA0cAMEQCIFFmHgu04hJg
        bQhybIXPqFCRbc6kZ2U9yL/KPtTPFAhbAiBA1m9g71FB5PdZCMdCU7FLRv378Hke
        TNYP6yrH7imDcA==
        -----END CERTIFICATE-----
        

peers:
  peer0.org3.ccb.com:
    url: grpcs://47.116.140.61:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAe2gAwIBAgIQCiwkvkSImGviDJW0vyotPDAKBggqhkjOPQQDAjBuMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEVMBMGA1UEChMMb3JnMy5jY2IuY29tMRswGQYDVQQDExJ0bHNjYS5v
        cmczLmNjYi5jb20wHhcNMjAxMTA5MDU0NTAwWhcNMzAxMTA3MDU0NTAwWjBuMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEVMBMGA1UEChMMb3JnMy5jY2IuY29tMRswGQYDVQQDExJ0bHNjYS5v
        cmczLmNjYi5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQXoPFffmXYrOUm
        qN4MxfAp5NLgxvYhC1NNcXwH5NOAR8MpVVUvVYraDLyTOcVD85ek/A4C/ojms4Do
        kWKmwGtFo20wazAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIG
        CCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIG6HuNurXNhtV7X7
        OvlZanG2DKegu2PBl3tHZ0UCteUTMAoGCCqGSM49BAMCA0cAMEQCIFFmHgu04hJg
        bQhybIXPqFCRbc6kZ2U9yL/KPtTPFAhbAiBA1m9g71FB5PdZCMdCU7FLRv378Hke
        TNYP6yrH7imDcA==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.org3.ccb.com
      hostnameOverride: peer0.org3.ccb.com
  peer1.org3.ccb.com:
    url: grpcs://47.116.140.61:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAe2gAwIBAgIQCiwkvkSImGviDJW0vyotPDAKBggqhkjOPQQDAjBuMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEVMBMGA1UEChMMb3JnMy5jY2IuY29tMRswGQYDVQQDExJ0bHNjYS5v
        cmczLmNjYi5jb20wHhcNMjAxMTA5MDU0NTAwWhcNMzAxMTA3MDU0NTAwWjBuMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEVMBMGA1UEChMMb3JnMy5jY2IuY29tMRswGQYDVQQDExJ0bHNjYS5v
        cmczLmNjYi5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQXoPFffmXYrOUm
        qN4MxfAp5NLgxvYhC1NNcXwH5NOAR8MpVVUvVYraDLyTOcVD85ek/A4C/ojms4Do
        kWKmwGtFo20wazAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIG
        CCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIG6HuNurXNhtV7X7
        OvlZanG2DKegu2PBl3tHZ0UCteUTMAoGCCqGSM49BAMCA0cAMEQCIFFmHgu04hJg
        bQhybIXPqFCRbc6kZ2U9yL/KPtTPFAhbAiBA1m9g71FB5PdZCMdCU7FLRv378Hke
        TNYP6yrH7imDcA==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.org3.ccb.com
      hostnameOverride: peer1.org3.ccb.com
certificateAuthorities:
  ca:
    url: https://47.116.140.61:7054
    caName: ca
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICQTCCAeigAwIBAgIRALDGAr3DhqG+4ZiCWUNyMBgwCgYIKoZIzj0EAwIwazEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xFTATBgNVBAoTDG9yZzMuY2NiLmNvbTEYMBYGA1UEAxMPY2Eub3Jn
        My5jY2IuY29tMB4XDTIwMTEwOTA1NDUwMFoXDTMwMTEwNzA1NDUwMFowazELMAkG
        A1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFu
        Y2lzY28xFTATBgNVBAoTDG9yZzMuY2NiLmNvbTEYMBYGA1UEAxMPY2Eub3JnMy5j
        Y2IuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjDefjiuDOD/QxZ+WGOaC
        7cfMXJMM9gCCCK0U5ZxocLZ91v8tJLoAZlZc/ZPH+5b6zyqPoqHYSb0T1etlcpMO
        ZKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
        BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCAx9QbiAdYVzsgq1AdK7udj
        jTWVS9ASgBhc1FD/zGYwYjAKBggqhkjOPQQDAgNHADBEAiBZaWq1fgu6X91vPNn4
        sUAjtke5h3LK2/F8EiFdSLgbMgIgc1P+Bhljo40AHWurEGLvaIS8hVSCLQTD0GAa
        leyDkbs=
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
